class symb_ctrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2020-04-16 22:50:43 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 10
        self.input_vars = ['']

    def move(self, ):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['dest2', 'dest1', 'loc']
        """
        output = dict()
        if self.state == 0:
            if True:
                self.state = 1

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 4
        elif self.state == 1:
            if True:
                self.state = 2

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 6
        elif self.state == 2:
            if True:
                self.state = 3

                output["dest2"] = True
                output["dest1"] = False
                output["loc"] = 7
        elif self.state == 3:
            if True:
                self.state = 4

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 6
        elif self.state == 4:
            if True:
                self.state = 5

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 4
        elif self.state == 5:
            if True:
                self.state = 6

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 5
        elif self.state == 6:
            if True:
                self.state = 7

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 8
        elif self.state == 7:
            if True:
                self.state = 8

                output["dest2"] = False
                output["dest1"] = True
                output["loc"] = 9
        elif self.state == 8:
            if True:
                self.state = 9

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 8
        elif self.state == 9:
            if True:
                self.state = 0

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 5
        elif self.state == 10:
            if True:
                self.state = 0

                output["dest2"] = False
                output["dest1"] = False
                output["loc"] = 5
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, ):
        raise ValueError("Unrecognized input: " + ().format())
