class symb_ctrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2020-04-16 18:22:10 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 14
        self.input_vars = ['park']

    def move(self, park):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['home', 'lot', 'X0reach', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (park == False):
                self.state = 2

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 3

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 1:
            if (park == False):
                self.state = 2

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 3

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 2:
            if (park == False):
                self.state = 4

                output["loc"] = 'X4'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 5

                output["loc"] = 'X4'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 3:
            if (park == False):
                self.state = 4

                output["loc"] = 'X4'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 5

                output["loc"] = 'X4'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 4:
            if (park == False):
                self.state = 6

                output["loc"] = 'X5'
                output["lot"] = True
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 7

                output["loc"] = 'X5'
                output["lot"] = True
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 5:
            if (park == False):
                self.state = 6

                output["loc"] = 'X5'
                output["lot"] = True
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 7

                output["loc"] = 'X5'
                output["lot"] = True
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 6:
            if (park == False):
                self.state = 8

                output["loc"] = 'X2'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = False
            elif (park == True):
                self.state = 9

                output["loc"] = 'X2'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 7:
            if (park == False):
                self.state = 8

                output["loc"] = 'X2'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = False
            elif (park == True):
                self.state = 9

                output["loc"] = 'X2'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 8:
            if (park == False):
                self.state = 10

                output["loc"] = 'X1'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 11

                output["loc"] = 'X1'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 9:
            if (park == False):
                self.state = 10

                output["loc"] = 'X1'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 11

                output["loc"] = 'X1'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 10:
            if (park == False):
                self.state = 12

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = True
            elif (park == True):
                self.state = 13

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = True
            else:
                self._error(park)
        elif self.state == 11:
            if (park == False):
                self.state = 12

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = True
            elif (park == True):
                self.state = 13

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = True
            else:
                self._error(park)
        elif self.state == 12:
            if (park == False):
                self.state = 2

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 3

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 13:
            if (park == False):
                self.state = 2

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            elif (park == True):
                self.state = 3

                output["loc"] = 'X3'
                output["lot"] = False
                output["X0reach"] = False
                output["home"] = False
            else:
                self._error(park)
        elif self.state == 14:
            if (park == False):
                self.state = 0

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = True
            elif (park == True):
                self.state = 1

                output["loc"] = 'X0'
                output["lot"] = False
                output["X0reach"] = True
                output["home"] = True
            else:
                self._error(park)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, park):
        raise ValueError("Unrecognized input: " + (
            "park = {park}; ").format(
                park=park))
